version: "3.7"
services:
  mongodb:
    image: mongo:4.2.2-bionic
    restart: always
    ports:
      - ${HOST_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    volumes:
      - ${HOST_DB_INIT_SCRIPT}:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongodb-data-db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  mongodb-data-db:
    driver: local